add lab 4
SapigaL/IOSLabs pull request #4
Opened 2019-12-11 10:32 UTC by SapigaL

2019-12-11 10:39 UTC, DrevychLuibomyr requested changes

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/HomeViewController.swift
> +    @IBAction func addNewData(_ sender: Any) {
нащо ця кнопка? Що вона мутить? Чому сендер Any якщо він втебе UIButton

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/HomeViewController.swift
> +        addButton.layer.cornerRadius = 33.5
дивись є метод setupVC мож туда ти кидаєш всі інші тип layer і тд то вони там мають бути

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +class addDataViewController: UIViewController,UITextFieldDelegate {
Final

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +    @IBOutlet weak var idField: UITextField!
модифікатори доступа

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +class addDataViewController: UIViewController,UITextFieldDelegate {
Поправ назву класу

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +class addDataViewController: UIViewController,UITextFieldDelegate {
Винеси UITextFieldDelegate в extension

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +
blank line

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +    var dataCar = CourseCar(id: "",nameCar: "",mark: "")
тут точно всі парам мають бути публічними

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +    var dataCar = CourseCar(id: "",nameCar: "",mark: "")
Чого ти тут його створює а не де працюєш з ним?

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +    private func FillCourse(){
не панятно що цей метод творить

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +        dataCar.id = idField.text!
воу трохи не так, чому ти не можеш зробити метод створишвши там dataCar і заповнити його даними з філда

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +        dataCar.id = idField.text!
+ якщо часто срається на optional то мож в структурі зробити поля опціональними але id ніт

2019-12-11 10:39 UTC, DrevychLuibomyr commented on Lab1/View Controllers/addDataViewController.swift
> +//print("response0")
не юзаєш видаляєш або марка

2019-12-11 11:03 UTC, DrevychLuibomyr commented
Не буде відформатованого коду, рахуй трохи буде жопа)

2019-12-11 11:08 UTC, SapigaL commented
Та я просто швидко кидав, то я знаю що код хуйово відіорматований, пофікшу

ср, 11 груд. 2019 о 13:03 DrevychLuibomyr <notifications@github.com> пише:

> Не буде відформатованого коду, рахуй трохи буде жопа)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SapigaL/IOSLabs/pull/4?email_source=notifications&email_token=AH3KGR2D5Z24V3XRCD6KJVLQYDCJFA5CNFSM4JZMWVXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGSXFII#issuecomment-564490913>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH3KGRYVE7KCJALXOHYWDCDQYDCJFANCNFSM4JZMWVXA>
> .
>

2019-12-11 11:13 UTC, DrevychLuibomyr commented
матюки не обов'язкові бо потім не я буду чекати пулл)

2019-12-11 11:14 UTC, SapigaL commented
Вибачте пане

ср, 11 груд. 2019 о 13:13 DrevychLuibomyr <notifications@github.com> пише:

> матюки не обов'язкові бо потім не я буду чекати пулл)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SapigaL/IOSLabs/pull/4?email_source=notifications&email_token=AH3KGR7W5CEH3DJ5GVO3KQLQYDDOVA5CNFSM4JZMWVXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGSX7DI#issuecomment-564494221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH3KGRYSUONTEVPKCZN2VXTQYDDOVANCNFSM4JZMWVXA>
> .
>

2019-12-12 05:11 UTC, DrevychLuibomyr requested changes

2019-12-12 05:11 UTC, DrevychLuibomyr commented on Lab1/View Controllers/SendNewCarInfo.swift
> +        let dataCar = CourseCar(id: idField.text!,nameCar: nameField.text!,mark: markField.text!)
! анврапни або дай моделі опціональні поля

2019-12-12 05:11 UTC, DrevychLuibomyr commented on Lab1/View Controllers/SendNewCarInfo.swift
> +    @IBAction private func onGetTapped(_ sender: Any) {
це можна винести в окреми метод

2019-12-12 05:11 UTC, DrevychLuibomyr commented on Lab1/View Controllers/SendNewCarInfo.swift
> +extension SendNewCarInfo:UITableViewDelegate {}
нащо тут таблиц ?

2019-12-12 05:11 UTC, DrevychLuibomyr commented on Lab1/View Controllers/SendNewCarInfo.swift
> +    private var FieldList  = [UITextField]()
використай камел кейс

2019-12-12 05:11 UTC, DrevychLuibomyr commented on Lab1/View Controllers/SendNewCarInfo.swift
> +        return patern.evaluate(with: fied.text!.trimmingCharacters(in: .whitespacesAndNewlines))
! - аврапни

2019-12-12 05:11 UTC, DrevychLuibomyr commented on Lab1/View Controllers/SendNewCarInfo.swift
> +
пуста лінія

2019-12-12 05:11 UTC, DrevychLuibomyr commented on Lab1/View Controllers/SendNewCarInfo.swift
> +extension SendNewCarInfo:UITableViewDelegate {}
Причина чому тому ти підписався на делегата таблиці яка?

2019-12-25 17:44 UTC, merged